### ISSUE TITLE
netCDF 4.7.2 compatability

### ISSUE THREAD

**Issue by vsaari** [hoene/libmysofa#105]
Latest version of netCDF(4.7.2, released in October) generates .sofa-files that are not opened. An example file is attached. 
[TestSOFA48_netcdf472.zip](https://github.com/hoene/libmysofa/files/4122054/TestSOFA48_netcdf472.zip) .

**Comment by hoene** [comment]
the problem is that the files are not backward compatible. 
I cannot read it with the legacy libsofa implemenntations.

Thus, I guess that we have an general issue that need to be address at the AES and the 69 standardization guys.

BTW:
check
https://github.com/hoene/libmysofa/tree/issue-105-netcdf-4.7.2

**Comment by vsaari** [comment]
It seems that netCDF assumes that a full implementation of HDF5 is used and they change their format within these limits when releasing new versions. So similar compatibility issues may appear every now and then when new versions of netCDF are released. In my opinion the advantage of libmysofa over other implementations is that is has no external libraries which it would need. With this in ming I think having things as they are at the moment and fixing possible compatibility issues with new versions of netCDF when they appear, would be a good way forward.

**Comment by hoene** [comment]
see #106
