### ISSUE TITLE
use semantic versioning

### ISSUE THREAD

**Issue by umlaeute** [hoene/libmysofa#107]
please consider using [semantic versioning](https://semver.org)

Semantic versioning mandates, that the **major version** (aka *soname*), only increases if the API changes in an incompatible way, e.g. because symbols were removed or their calling convention changed (but mostly because symbols were removed).

I don't see any such change for the recent `1.0.0` release, so I guess the soname bump for this release was accidental (in theory you can have a "sales version" that is independent of the "technical (semantic) version"; in practice, build systems like CMake need extra care to handle this properly). see also #23 

Alternatively, the `1.0.0` release indicates that the API is now mature enough to leave the `0.x` *alpha* stage behind; so the `1.x` series is a promise to the (dev)user that the API is indeed stable.
this would be inline with the code name "Grown up", but the changelog (as seen on the [release page](https://github.com/hoene/libmysofa/releases/tag/v1.0)) doesn't indicate anything like this beyond the codename.

please clarify the project's position on versioning.

**Comment by hoene** [comment]
libmysofa did not had a breaken API change since it is on github. Thus, also 1.0.0 does not break the API.

Libmysofa is now three years old. Several security experts have challenged it. And it is now adopted by the HRTF producting industry. 

 Version 1.0.0 brings with support of netcdf 4.7.2 some major feature improvement. Also, since 0.6 we have collected a couple of fixed security issues. Thus, I guess the API is now so mature that I do not know on how to improve it.

But @umlaeute , you are the expert. Shall I remove version 1.0.0 and name it 0.9.2?

**Comment by umlaeute** [comment]
so the only reason to switch to `1.0.0` is to proclaim, that the API/ABI is stable. (i just realized that i wrote *API* when i was really talking about *ABI*; but i figure that what you say is true for the ABI as well).

i think this proclamation is a good reason to announce `1.0.0`.

but a soname-bump comes at a cost for distributions (everything that links to libmysofa will have to be rebuilt).
so in the future, please do not do a soname bump (e.g. by naively creating a `2.0.0` release) "just because" the previous release was `1.9` or because an important feature was added.
