### ISSUE TITLE
resampling always active?

### ISSUE THREAD

**Issue by richardpl** [hoene/libmysofa#12]
By inspecting code there appears resampling is always done and there is no way to avoid it?

**Comment by hoene** [comment]
What would you suggest?
Setting sampling rate to NULL at loading?

**Comment by richardpl** [comment]
There should be way to get sample rate of HRTFs. So one can use that instead of whatever is input audio.

**Comment by hoene** [comment]
I would suggest to use mysofa_load instead of mysofa_open.
See 
https://github.com/hoene/libmysofa/blob/master/src/hrtf/easy.c
for an example.

Changing the easy interface might causes problems at other parts of the normalization code.

Or you open the file for different sampling rates multiple times.

**Comment by hoene** [comment]
The problem is that sampling rates in SOFA files can be defined per filter. Each direction can have its own sampling rate. I do not believe that you like to handle all those cases.

Instead, just take 48000 or 44100 and you will be happy...

**Comment by richardpl** [comment]
I yet have to encounter such files where sampling rate differs per each filter.

**Comment by petibub** [comment]
We load multiple SOFA files using the mysofa library. Each of those files can have different sampling rate. We use mysofa_load for that in a loop - it works perfectly for us...
