### ISSUE TITLE
cannot open SOFA files from IRCAM

### ISSUE THREAD

**Issue by holopeat** [hoene/libmysofa#131]
I downloaded a few SOFA files from here: http://opendap.ircam.fr/hyrax/SimpleFreeFieldHRIR/BILI/COMPENSATED_INTERPOLATED/48000/ using the "Get as NetCDF 4" button and tried to open them using libmysofa. I am getting an unsupported format error with the message "FHDB type 3 unsupported values" generated in `fractalhead.c`, line 126.

So there is a compatibility issue here, although I do not know if the file is wrong or the lib is processing it wrong.

Any help on this would be much appreciated.

Cheers, Peat

**Comment by petibub** [comment]
I have just tried to load the data from IRCAM in Matlab SOFA API, the reference implementation for SOFA. 

I tried: 
* http://bili2.ircam.fr/SimpleFreeFieldSOS/BILI/COMPENSATED_INTERPOLATED/48000/IRC_1100_I_SOS24_48000.sofa
* http://bili2.ircam.fr/SimpleFreeFieldSOS/BILI/COMPENSATED_INTERPOLATED/48000/IRC_1100_I_SOS24_48000.sofa.nc4
* http://bili2.ircam.fr/SimpleFreeFieldSOS/BILI/COMPENSATED_INTERPOLATED/48000/IRC_1100_I_SOS24_48000.sofa.nc
In all these cases, the Matlab API threw a “load error”. 
* Direct access to http://bili2.ircam.fr:80/SimpleFreeFieldSOS/BILI/COMPENSATED_INTERPOLATED/48000/IRC_1100_I_SOS12_48000.sofa resulted in "access denied".

A deep inspection of the nc4 file showed that it contains a global attribute called "Data.SamplingRate.Units". This is not compliant with the AES69/SOFA standard (global attributes must not contain "." and Data.SamplingRate.Units must be an attribute of the variable "Data.SamplingRate"). I guess it's just a small bug in the IRCAM files. 

So, the problem is not at libmysofa. I know that this does not help - maybe you want to contact IRCAM's admin?
Regards, 
Piotr

**Comment by holopeat** [comment]
I am sorry, but it seems like I sent a link to the wrong files, which apparently do not conform to the specifiction. The valid SOFA files which are stored in this [archive](http://opendap.ircam.fr/Archives/SimpleFreeFieldHRIR/BILI/COMPENSATED_INTERPOLATED/48000/contents.html), on the other hand, can be opened by the Matlab SOFA API, but they cannot be opened by libmysofa.
