### ISSUE TITLE
slow loading of sofa files

### ISSUE THREAD

**Issue by richardpl** [hoene/libmysofa#14]
When trying to load big sofa files, it takes several seconds, where previously it would take most 1 second (with sofalizer from FFmpeg using NetCDF directly).

**Comment by hoene** [comment]
May you share this file with me?

**Comment by hoene** [comment]
Reading the SOFA files should not differ to much. (mysofa_load should be as fast as the reference implementation).

That takes time is the normalization and the process of building the lookup structures.

For me, the filter lookup times were the first prio. With the reference implementation, filter lookup takes O(N) instead of O(log n).

Also, the interpolation of HRTFs is done in O(1) instead of O(N).

**Comment by richardpl** [comment]
It is with mysofa_open, link: http://sofacoustics.org/data/database/fhk/HRIR_FULL2DEG.sofa

Another issue I found is if previously call mysofa_load, and later mysofa_open with same sofa file and sample rate to one reported in mysofa_load, length of IRs: N changes.
The resulted IRs are bad, because I get artifacts when filtering in time domain, the one in frequency domain are still present but much less noticeable.

**Comment by hoene** [comment]
Currently, I am working on a more complex minphase filter. It may reduce the artifacts. For the time being, I will switch of the minphase filter. This should reduce the loading times, too.

**Comment by hoene** [comment]
@richardpl 
May you check https://github.com/hoene/libmysofa/commit/640aff422a3c2f1d7045c4837f5464a013efab56
whether things got better?

**Comment by richardpl** [comment]
Yes it got better.
