### ISSUE TITLE
Error when trying to load a very dense HRTF

### ISSUE THREAD

**Issue by dgonzalezt** [hoene/libmysofa#205]
Hello, 

We have resampled a sofa from the ARI library in Matlab to one degree and generated a sofa file. That new sofa file now has 41527 source positions, and the Data.IR field has dimensions of 41527x2x256.

When we try to load it using libmysofa, we get a MYSOFA_INVALID_FORMAT error, specifically on line 270 of btree.c.

We can think of a very basic solution that is simply to change the previous check (line 269), changing "elements >= 0x100000" to "elements >= 0x130000" obviously works and seems to load correctly. But we don't know if it has any consequences that we don't foresee. I attach the sofa file in question.

Thank you very much. 

Daniel
[latTestAziBeRTA_Resamp1_Fran.zip](https://github.com/hoene/libmysofa/files/12726772/latTestAziBeRTA_Resamp1_Fran.zip)

**Comment by hoene** [comment]
May I use your zip file for our unit tests?

**Comment by dgonzalezt** [comment]
Yes, of course.

**Comment by HaHeho** [comment]
I can confirm that `MYSOFA_INVALID_FORMAT` appears when trying to load this [KEMAR HRIR from RWTH](https://publications.rwth-aachen.de/record/807373/files/Kemar_HRTF_sofa.sofa) with 64800 points. I assume that this file should be valid otherwise.

**Comment by HaHeho** [comment]
I am trying to do some hacky things and load binaural room impulse responses instead of anechoic HRIRs (packaged as a SimpleFreeFieldHRIR since this is the only convention this API accepts). The size limit is triggered by many directions but also by an extended length of the impulse responses (which may be magnitudes higher for non-anechoic data).

The hard-coded limitation of the data size seems arbitrary. Why does it exist at all?

**Comment by HaHeho** [comment]
> Due to security reasons, we limit the input values are limited to (somewhat) arbitrary values. This prevents also a too high memory consumption.

But I would say this also prevents certain use cases of this API. Would you want to have the size limit optional or configurable during compile time?

**Comment by hoene** [comment]
fixed with #208

**Comment by ThreeDeeJay** [comment]
> Due to security reasons, we limit the input values are limited to (somewhat) arbitrary values.

@hoene Is that related to the denial of service attack mentioned in https://github.com/hoene/libmysofa/issues/195#issuecomment-1370881871?
Was it confirmed to be a DoS attack or was it just a misunderstanding from an unexpected/malformed SOFA file or something like that?

I'm asking because even with the latest limit size increase, I still wasn't even able to convert even a [5 degree (~100MB) EAC HRTF SOFA](https://mega.nz/file/zOZTSIyT#TLnY4CeqVzwgH2_w3mrqAaT6NUgNYN_x57EXHJE4anM) until I [removed the limit altogether](https://github.com/ThreeDeeJay/libmysofa/commit/aa9e7865b59990ebd966919e565c7ee080a88c23) as I mentioned [here](https://github.com/hoene/libmysofa/issues/195#issuecomment-1382665204), but I don't want to put users at risk either 😅

Would increasing the limit to 128MB be within the safe threshold?
I think it would yield enough wiggle room to fix 5 degree (default) EAC SOFAs then with a new release tag I could update OpenAL Soft's end since the [dev requested a stable release to pull](https://github.com/kcat/openal-soft/pull/783#discussion_r1024772786).

**Comment by dgonzalezt** [comment]
But @ThreeDeeJay  the limit is per number of IRs, isn't it?  In case it helps, it already works for us, it loads 140Mb SOFA files.  But maybe I'm misunderstanding what you're doing, I don't want to mess you up.

**Comment by HaHeho** [comment]
The length of the IRs also matters towards the size limit. I also assume the number of ears (which should usually/always be two anyway).

However, I did not understand how the number of measurements and samples contributed to the size limit without debugging and digging into the code. Having that documented in the code or somewhere else would be nice.

**Comment by dgonzalezt** [comment]
Good morning. @ThreeDeeJay I found out by debugging. I compiled the library with the VDEBUG preprocessor definition and using the test app that comes with the library, all this in windows. And nothing more, patience and chasing the point where it comes out of the execution.
