### ISSUE TITLE
Patch: Fix shared build on mingw-w64 windows

### ISSUE THREAD

**Issue by Adsun701** [hoene/libmysofa#36]
Hi there.

I found that when building a shared version of libmysofa on Windows using mingw-w64 on MSYS2, it fails with undefined references to the zlib library:

```
CMakeFiles/mysofa-shared.dir/objects.a(gunzip.c.obj):gunzip.c:(.text+0x5e): undefined reference to `inflateInit_'
CMakeFiles/mysofa-shared.dir/objects.a(gunzip.c.obj):gunzip.c:(.text+0x71): undefined reference to `inflate'
CMakeFiles/mysofa-shared.dir/objects.a(gunzip.c.obj):gunzip.c:(.text+0x81): undefined reference to `inflateEnd'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/mysofa-shared.dir/build.make:590: src/libmysofa.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:88: src/CMakeFiles/mysofa-shared.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

So I wrote a patch that corrects linking with zlib _and_ allows installation of both the dll and dll.a files instead of just the dll file without the dll.a file. Here's the link.
[https://github.com/Adsun701/MINGW-packages/blob/master/mingw-w64-libmysofa/0001-libmysofa-0.6-fix-undefined-linking-for-shared-build.patch](url)

Thanks!

Andy

**Comment by hoene** [comment]
Hi Andy,

thanks for the patch.

It contains two issues.

First, if you use a mingw-w64 windows environment, the ZLIB_LIBRARIES variable is not set correctly.

Second, it adds both static and dynamic file to the both the static and dynamic packages.

First is reasonable, if you add a correct statement that applied only in your environment.

Latter does not make sense because.

PS:
I would need a former github pull request instead of a patch.
