### ISSUE TITLE
remove check condition for ReceiverPosition

### ISSUE THREAD

**Issue by gooderist** [hoene/libmysofa#58]
Hello, I have files which fail mysofa_check (check.c: 137) because of the requirement that ReceiverPosition.values[1] be negative. We generate files with a positive values[1] and negative values[4]. Would it be okay to either remove the line or change it to `!fequals(hrtf->ReceiverPosition.values[1], 0)` ?

**Comment by hoene** [comment]
hmm, that is not enough. You then have to switch the coordinates because front becomes back and vice versa.

Actually, a rotation matrix is then needed to change the all sources coordinates accordingly.

**Comment by funkerresch** [comment]
Hi, we came across the same issue. We think the question is where the left and right ear data is stored in .Data.IR.

There seems to be no restriction in the AES69 standard and actually confusion across implementations. The default value in AES69 for .ReceiverPosition is [0 .09 0; 0 -.09 .0] (left ear first), libmysifa and the Matlab API assume [0 -.09 0; 0 .09 0] (right ear first).

If you expect the ears to be stored in a certain order we could switch the values in .Data.IR in this case: Data.IR = cat(2, Data.IR[:,2,:], Data.IR[:,1,:]).

However, this only solves the problem, if people are using the SOFA format correctly, which is not the case. For example, in TU-Berlin_QU_KEMAR_anechoic_radius_0.5m.sofa the ReceiverPosition suggests that the right ear is saved first. A plot of the data indicates that this is not the case.

We suggest to remove the lines completely for this reason, and also because the x and z positions of the receiver can actually deviate from 0. For example, in numerically simulated HRTFs where the receiver position can be given by a vibrating element in the 3D head mesh. This element should have x/z coordinates close to 0 but not necessarily equal to 0.

A different check seems difficult. We could check for the RMS values of HRIRs close to azimuth=90 and elevation=0. The HRIR with the larger RMS should be the left ear HRIR. However, this might be tricky if such source positions are not included.

Best, Thomas and Fabian

**Comment by hoene** [comment]
The most important thing is that the mysofa API must remain simple.

If the ears are on any other position, this has to be corrected by a transform operation. Otherwise, the programs using libmysofa will breaks.

Do you want to provide a patch that transform the coordinates?

**Comment by petibub** [comment]
Hi guys, 

I think that I can contribute to the standard issue: as for the standard, I guess you talk about the conventions "SimpleFreeFieldHRIR", aren't you? 

For this conventions, the standard (from the AES), the website (sofaconventions.org) and the MATLAB API  - they all deal with the left ear as the first channel and right ear as the second channel. See Fig D.1 and Tab. D.4B in the standard, and the figure and table at https://www.sofaconventions.org/mediawiki/index.php/SimpleFreeFieldHRIR.

While some SOFA files might be incorrectly encoded, the standard and the reference implementation (Matlab API) seem to be correct (prove me wrong, if I miss something!). 

And, as you probably know, in audio left is always the first channel :-)

Regards, Piotr

**Comment by funkerresch** [comment]
Hi, a simple solution would be to return different error codes and let applications that use libmysofa handle it themselves? Errors could be encoded bitwise and accumulated in mysofa_open_default(). mysofa_open_default() could still return the MYSOFA_EASY struct if, for instance, the right channel is first?
Regards, Thomas

**Comment by petibub** [comment]
> Hi, a simple solution would be to return different error codes and let applications that use libmysofa handle it themselves? Errors could be encoded bitwise and accumulated in mysofa_open_default(). mysofa_open_default() could still return the MYSOFA_EASY struct 

That's a great idea!

> if, for instance, the right channel is first?

This would be an invalid SOFA file. I don't think that we should provide solutions to repair poorly saved data. If we start trusting swapped receiver channels, how do we know that other things aren't wrong like wrong sampling rate or mixed time index in the impulse responses, or even wrong coordinate system...

**Comment by funkerresch** [comment]
As I understand the AES69 standard, neither .ReceiverPosition [0 .09 0; 0 -.09 .0] nor .ReceiverPosition [0 -.09 0; 0 .09 .0 are invalid. That's what I meant by right channel first..
Regards,
Thomas

**Comment by f-brinkmann** [comment]
@petibub, I also go by left first and feel this is a somewhat agreed standard in the audio community. Does AES69 enforce this? In AES69, there are examples for left first (D.4B) and right first (Table D.5D).

**Comment by petibub** [comment]
Dear Thomas,

> As I understand the AES69 standard, neither .ReceiverPosition [0 .09 0; 0 -.09 .0] nor .ReceiverPosition [0 -.09 0; 0 .09 .0 are invalid. That's what I meant by right channel first..

I agree - the standard does not impose any channel ordering. But the conventions "SimpleFreeFieldHRIR" does. When I said "standard", I was talking in the context of libmysofa, which reads SimpleFreeFieldHRIRs only. Sorry for the confusion!

Dear Fabian, 

> @petibub, I also go by left first and feel this is a somewhat agreed standard in the audio community. Does AES69 enforce this?

AES69 does not, but SimpleFreeFieldHRIR does. For the sake of simplicity... :-)

> In AES69, there are examples for left first (D.4B) and right first (Table D.5D).

I just had a look at D.5D: wow, it's a bug (typo). thanks for finding that! You can see the bug when comparing ReceiverDescription, that says "... left and right ears correspond to the first and second receivers, respectively", with RecevierPosition which says "[0 -0.09 0; ...". We'll be updating the standard this year, and we can fix it. So thanks for spotting this problem!

Regards, 
Piotr

**Comment by hoene** [comment]
@f-brinkmann @funkerresch Thank you both for helping us to clarify the issue. Appreciated!

**Comment by f-brinkmann** [comment]
@hoene: Should @funkerresch and me draft a patch with the bit-wise error coding? At the moment 'correct' (left first) SOFA files are still not read and throw an error and 'incorrect' (right first) files are read.

**Comment by hoene** [comment]
Hi guys,

are you available for a call? (+49 170 2025755)

 

Von: f-brinkmann <notifications@github.com> 
Gesendet: Montag, 2. März 2020 14:54
An: hoene/libmysofa <libmysofa@noreply.github.com>
Cc: Christian Hoene <christian.hoene@symonics.com>; Mention <mention@noreply.github.com>
Betreff: Re: [hoene/libmysofa] remove check condition for ReceiverPosition (#58)

 

@hoene <https://github.com/hoene> : Should @funkerresch <https://github.com/funkerresch>  and me draft a patch with the bit-wise error coding? At the moment 'correct' (left first) SOFA files are still not read and throw an error and 'incorrect' (right first) files are read.

**Comment by hoene** [comment]
see #120
